name: eliud_pkg_feed
description: Eliud package for feed, friends, etc
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  transparent_image: 2.0.0
  flutter_stage: 0.0.1
#  flutter_tagging: 3.0.0

  eliud_core:
    path: ../eliud_core

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_text:
    path: ../eliud_pkg_text

  eliud_pkg_etc:
    path: ../eliud_pkg_etc

  eliud_pkg_medium:
    path: ../eliud_pkg_medium

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/basicons.xyz/
    - assets/images/manypixels.co/
    - assets/images/undraw.co/
    - assets/images/pexels.com/
    - assets/images/segoshvishna.fiverr.com/
