---
name: eliud_pkg_feed
description: eliud_pkg_feed is a package to provide a social media feed functionality
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_feed
version: 1.1.5+7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  chips_input: ^0.1.0
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core: ^1.1.5+7
  eliud_pkg_follow: ^1.1.5+5
  eliud_pkg_medium: ^1.1.5+5
  eliud_pkg_membership: ^1.1.5+5
  eliud_pkg_notifications: ^1.1.5+5
  eliud_pkg_text: ^1.1.5+6
  eliud_pkg_etc: ^1.1.5+8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  pointer_interceptor: ^0.9.3+6
  tuple: ^2.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.5+2
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/basicons.xyz/
  - assets/images/manypixels.co/
  - assets/images/undraw.co/
  - assets/images/pexels.com/
  - assets/images/segoshvishna.fiverr.com/
  - assets/images/icons8.com/
platforms:
  android: null
  ios: null
  web: null
