name: eliud_pkg_feed
description: Eliud package for feed, friends, etc
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  buttons_tabbar: ^1.1.1
  flutter_staggered_grid_view: 0.3.4

  eliud_core:
    path: ../eliud_core

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_album:
    path: ../eliud_pkg_album

  eliud_pkg_post:
    path: ../eliud_pkg_post

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/basicons.xyz/
