name: eliud_pkg_feed
description: Eliud package for feed, friends, etc
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  buttons_tabbar: ^1.2.1
  flutter_staggered_grid_view: 0.4.0
  flutter_carousel_slider: 1.0.8
  transparent_image: 2.0.0
  flutter_stage: 0.0.1
  pinch_zoom: ^0.1.0-nullsafety.0
  percent_indicator: 3.0.1
  camera: 0.8.1
  video_player: 2.1.1
  chewie: 1.0.0
  image_picker_gallery_camera: 0.2.2
  file_picker: 3.0.1

  eliud_core:
    path: ../eliud_core

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_text:
    path: ../eliud_pkg_text

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/basicons.xyz/
    - assets/images/manypixels.co/
    - assets/images/undraw.co/
    - assets/images/pexels.com/
    - assets/images/segoshvishna.fiverr.com/
