---
name: eliud_pkg_feed
description: eliud_pkg_feed is a package to provide a social media feed functionality
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_feed
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
#  chips_input: ^0.1.0
  eliud_core: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_core_model: ^1.3.0
  eliud_pkg_etc: ^1.3.0
  eliud_pkg_follow: ^1.3.0
  eliud_pkg_feed_model: ^1.3.0
  eliud_pkg_follow_model: ^1.3.0
  eliud_pkg_medium: ^1.3.0
  eliud_pkg_membership: ^1.3.0
  eliud_pkg_notifications: ^1.3.0
  eliud_pkg_text: ^1.3.0
  bloc: ^8.1.4
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  pointer_interceptor: ^0.10.1+2
  tuple: ^2.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/basicons.xyz/
  - assets/images/manypixels.co/
  - assets/images/undraw.co/
  - assets/images/pexels.com/
  - assets/images/segoshvishna.fiverr.com/
  - assets/images/icons8.com/
platforms:
  android: null
  ios: null
  web: null
